-- 040 — Apply the lower accessory volume retroactively to ACTIVE routines.
-- 039 only changed the periodization fallback, which affects new routines and
-- slots that left series/reps NULL. Already-approved skeletons carry per-slot
-- accessory series/reps the AI chose under the old prompt (up to 3 × "10 a 12"),
-- so bring those down too.
--
-- Scope and safety:
--   · Only accessories of skeletons still 'approved' (the routines athletes run
--     today). Pending ones get regenerated by the new prompt; superseded/
--     rejected are history.
--   · Series 3 → 2. Finishers/pyramids are already 2, so they're untouched.
--   · Only the high plain rep ranges fall to "6 a 8". Special schemes
--     (finisher "10x10x10", pyramid "10 - 8 - 6", timed/core like "30 seg",
--     "10") and already-low values are left exactly as they are.
--   · Athlete progression (athlete_exercise_weights.current_reps_text) is NOT
--     reset — at runtime it overrides slot.reps, so earned reps are preserved.

UPDATE skeleton_slots s
   SET series = 2
  FROM athlete_skeletons k
 WHERE s.skeleton_id = k.id
   AND k.status = 'approved'
   AND s.role = 'accesorio'
   AND s.series = 3;

UPDATE skeleton_slots s
   SET reps = '6 a 8'
  FROM athlete_skeletons k
 WHERE s.skeleton_id = k.id
   AND k.status = 'approved'
   AND s.role = 'accesorio'
   AND s.reps IN ('8 a 10', '10 a 12', '10 a 15', '12 a 15');
