import { Router } from 'express';
import onboarding from './onboarding.js';
import athlete from './athlete.js';
import coach from './coach.js';
import auth from './auth.js';
import sessions from './sessions.js';
import alerts from './alerts.js';
import exercises from './exercises.js';
import profile from './profile.js';

const router = Router();
router.use('/auth', auth);
router.use('/onboarding', onboarding);
router.use('/athlete', athlete);
router.use('/coach', coach);
router.use('/sessions', sessions);
router.use('/alerts', alerts);
router.use('/exercises', exercises);
router.use('/profile', profile);
export default router;
