import { Router } from 'express';
import onboarding from './onboarding.js';
import athlete from './athlete.js';
import auth from './auth.js';
import sessions from './sessions.js';
import alerts from './alerts.js';
import exercises from './exercises.js';
import profile from './profile.js';
import pushRouter from './push.js';
import progressRouter from './progress.js';
import billing from './billing.js';
import adminOps from './admin-ops.js';
import adminAlerts from './admin-alerts.js';
import rutinas from './rutinas.js';
import adminRutinasRouter from './admin-rutinas.js';
import adminExercises from './admin-exercises.js';
import admin from './admin.js';
import platformFee from './platform-fee.js';

const router = Router();
router.use('/auth', auth);
router.use('/onboarding', onboarding);
router.use('/athlete', athlete);
router.use('/sessions', sessions);
router.use('/alerts', alerts);
router.use('/exercises', exercises);
router.use('/profile', profile);
router.use('/push', pushRouter);
router.use('/progress', progressRouter);
router.use('/billing', billing);
router.use('/admin/operations', adminOps);
router.use('/admin/alerts', adminAlerts);
router.use('/admin/rutinas', adminRutinasRouter);
router.use('/admin/rutinas', rutinas);
router.use('/admin/exercises', adminExercises);
router.use('/platform-fee', platformFee);
router.use('/admin', admin);
export default router;
